Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -1,90 +1,103 @@
-name: Android CI
+name: MediaVox Release CI
 
 on:
   push:
-    branches: [ "alpha" ]
-    paths-ignore:
-      - ".github/**"
-      - "!.github/workflows/**"
-      - ".idea/"
-      - "fastlane/"
-      - '.gitignore'
-      - "*.md"
-      - "LICENSE"
-  pull_request:
-    branches: [ "alpha" ]
-    paths-ignore:
-      - ".github/**"
-      - "!.github/workflows/**"
-      - ".idea/"
-      - "fastlane/"
-      - '.gitignore'
-      - "*.md"
-      - "LICENSE"
-  workflow_dispatch:
+    branches:
+      - nastu
 
 jobs:
   build:
-    name: Build App
+
     runs-on: ubuntu-latest
+    permissions:
+      contents: write
+      pull-requests: write
+      repository-projects: write
+      
     steps:
-
       - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v4
+      - name: set up JDK 17
+        uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
           cache: gradle
 
-      - name: Set release type
-        run: echo releaseType=CI > package.properties
+      - name: Grant execute permission for gradlew
+        run: chmod +x gradlew
 
-      - name: Create signing files
-        if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip_signing_apk]')
+      - name: Find libs.versions.toml
+        id: find_libs_versions
         run: |
-          mkdir -p ~/.gradle
-          echo "${{ secrets.KEYSTORE_SECRET }}" | base64 -d > ~/key.jks
-          echo "AKANE_RELEASE_STORE_FILE=$(realpath ~/key.jks)" > ~/.gradle/gradle.properties
-          echo "AKANE_RELEASE_STORE_PASSWORD=${{ secrets.KEYSTORE_PWD }}" >> ~/.gradle/gradle.properties
-          echo "AKANE_RELEASE_KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> ~/.gradle/gradle.properties
-          echo "AKANE_RELEASE_KEY_PASSWORD=${{ secrets.KEY_PWD }}" >> ~/.gradle/gradle.properties
-
-      - name: Build with Gradle
-        run: ./gradlew :app:assembleRelease
-
-      - name: Find apk
+          find . -type f -name "libs.versions.toml" -print -quit > libs_versions_path.txt || echo "File not found"
+          if [ -s libs_versions_path.txt ]; then
+            echo "::set-output name=libs_versions_path::$(cat libs_versions_path.txt)"
+          else
+            echo "::set-output name=libs_versions_path::"
+          fi
+      - name: Retrieve Previous Version Code
+        id: retrieve_previous_version
         run: |
-          echo "APK_FILE_X64=$(find app/build/outputs/apk/release -name '*-x86_64-*.apk')" >> $GITHUB_ENV
-          echo "APK_FILE_ARM64=$(find app/build/outputs/apk/release -name '*-arm64-v8a-*.apk')" >> $GITHUB_ENV
-          echo "APK_FILE_UNIVERSAL=$(find app/build/outputs/apk/release -name '*-universal-*.apk')" >> $GITHUB_ENV
-          GIT_COMMIT_HASH=$(git rev-parse --short HEAD)
-          ACCORD_VERSION=$(grep "versionName" app/build.gradle.kts | awk -F'"' '{print $2}' | head -n 1)
-          APK_FILE_NAME=Accord-$ACCORD_VERSION-$GIT_COMMIT_HASH
-          echo "APK_FILE_NAME_X64=$APK_FILE_NAME-x86_64" >> $GITHUB_ENV
-          echo "APK_FILE_NAME_ARM64=$APK_FILE_NAME-arm64-v8a" >> $GITHUB_ENV
-          echo "APK_FILE_NAME_UNIVERSAL=$APK_FILE_NAME-universal" >> $GITHUB_ENV
-
-      - name: Upload x86_64 apk
+          if [ -n "${{ steps.find_libs_versions.outputs.libs_versions_path }}" ]; then
+            previous_version=$(awk -F "=" '/app-version-previousCode/ {print $2}' "${{ steps.find_libs_versions.outputs.libs_versions_path }}"|  tr -d '[:space:]' | tr -d '"')
+            echo "::set-output name=previous_version::$previous_version"
+          else
+            echo "No libs.versions.toml found"
+            echo "::set-output name=previous_version::0"  # Default to 0 if file not found
+          fi
+          
+      - name: Get Current Version Code app-version-previousCode
+        id: get_current_version
+        run: |
+          if [ -n "${{ steps.find_libs_versions.outputs.libs_versions_path }}" ]; then
+            current_version=$(awk -F "=" '/app-version-versionCode/ {print $2}' "${{ steps.find_libs_versions.outputs.libs_versions_path }}" | tr -d '[:space:]' | tr -d '"')
+            echo "::set-output name=current_version::$current_version"
+          else
+            echo "No libs.versions.toml found"
+            echo "::set-output name=current_version::0"  # Default to 0 if file not found
+          fi
+          
+      - name: Rescue Build
+        run: |
+          ./gradlew assembleDebug
+          echo "APK_FILE=$(find app/build/outputs/apk/debug -name '*.apk')" >> $GITHUB_ENV
+          export APK_FILE=$(find app/build/outputs/apk/debug -name '*.apk')
+          echo "APK_FILE_NAME=$(basename $APK_FILE .apk)" >> $GITHUB_ENV
+      - name: Upload Build App
         uses: actions/upload-artifact@v4
         with:
-          name: ${{ env.APK_FILE_NAME_X64 }}
-          path: ${{ env.APK_FILE_X64 }}
+          name: ${{ env.APK_FILE_NAME }}
+          path: ${{ env.APK_FILE }}
           compression-level: 9
-
-      - name: Upload arm64-v8a apk
-        uses: actions/upload-artifact@v4
+          
+      - name: Update changelogs
+        uses: Bullrich/generate-release-changelog@master
+        id: Changelog
+        if:  ${{ steps.retrieve_previous_version.outputs.previous_version }} != ${{ steps.get_current_version.outputs.current_version }}
+        env:
+          REPO: ${{ github.repository }}
+          
+      - name: Generate Release Build
+        id: create_release
+        uses: actions/create-release@latest
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
-          name: ${{ env.APK_FILE_NAME_ARM64 }}
-          path: ${{ env.APK_FILE_ARM64 }}
-          compression-level: 9
-
-      - name: Upload universal apk
-        uses: actions/upload-artifact@v4
+         tag_name: v1.${{ steps.get_current_version.outputs.current_version }}
+         release_name: ${{ github.event.repository.name }} v1.${{ steps.get_current_version.outputs.current_version }}
+         body: |
+            ${{ steps.Changelog.outputs.changelog }}
+         draft: false
+         prerelease: false
+          
+      - name: Upload Release APK
+        id: upload_release_asset
+        uses: actions/upload-release-asset@latest
+        env:
+         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
-          name: ${{ env.APK_FILE_NAME_UNIVERSAL }}
-          path: ${{ env.APK_FILE_UNIVERSAL }}
-          compression-level: 9
+         upload_url: ${{ steps.create_release.outputs.upload_url }}
+         asset_path: ${{ env.APK_FILE }}
+         asset_name:  ${{ env.APK_FILE_NAME }}.apk
+         asset_content_type: application/zip
